import { StyleSheet } from "react-native";
import { AppTheme } from "../../global/themes";

export function createStyles(theme: AppTheme) {
  const isDark = theme.mode === "dark";

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    contentContainer: {
      paddingTop: 64,
      paddingBottom: 140,
      paddingHorizontal: 20,
    },
    brandRow: {
      alignItems: "flex-start",
      marginBottom: 6,
    },
    brandLogo: {
      width: 138,
      height: 42,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    addressText: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: "600",
      maxWidth: "76%",
    },
    notificationButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.colors.surfaceElevated,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      position: "relative",
    },
    notificationIcon: {
      color: theme.colors.textSecondary,
      fontSize: 10,
      fontWeight: "700",
    },
    notificationBadge: {
      position: "absolute",
      top: -4,
      right: -4,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.colors.accent,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    notificationBadgeText: {
      color: "#FFFFFF",
      fontSize: 10,
      fontWeight: "700",
    },
    greetingRow: {
      marginTop: 24,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    greetingText: {
      color: theme.colors.textPrimary,
      fontSize: 30,
      fontWeight: "700",
    },
    loginChip: {
      borderWidth: 1,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surfaceElevated,
      borderRadius: 18,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    loginChipText: {
      color: theme.colors.primary,
      fontWeight: "700",
      fontSize: 13,
    },
    guestHelperText: {
      marginTop: 10,
      color: theme.colors.textSecondary,
      fontSize: 14,
    },
    runtimeChip: {
      marginTop: 10,
      alignSelf: "flex-start",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    runtimeChipWarning: {
      borderColor: theme.colors.primary,
    },
    runtimeChipError: {
      borderColor: theme.colors.accent,
    },
    runtimeChipTitle: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    runtimeChipText: {
      marginTop: 3,
      color: theme.colors.textSecondary,
      fontSize: 11,
      fontWeight: "600",
    },
    categoriesGrid: {
      marginTop: 22,
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 12,
    },
    categoryCard: {
      width: "48.5%",
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      paddingVertical: 12,
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    categoryIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.colors.surfaceElevated,
      alignItems: "center",
      justifyContent: "center",
    },
    categoryIconText: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: "700",
    },
    categoryLabel: {
      marginTop: 8,
      color: theme.colors.textPrimary,
      fontSize: 12,
      fontWeight: "600",
      textAlign: "center",
    },
    bannerCard: {
      marginTop: 24,
      borderRadius: 24,
      backgroundColor: isDark ? theme.colors.surfaceElevated : "#111111",
      padding: 20,
      borderWidth: 1,
      borderColor: theme.colors.primary,
    },
    bannerOverline: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    bannerTitle: {
      marginTop: 10,
      color: "#FFFFFF",
      fontSize: 28,
      fontWeight: "800",
      lineHeight: 32,
    },
    bannerSubtitle: {
      marginTop: 10,
      color: "#F3F3F3",
      opacity: 0.88,
      fontSize: 14,
      lineHeight: 20,
    },
    bannerButton: {
      marginTop: 16,
      alignSelf: "flex-start",
      borderRadius: 18,
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    bannerButtonText: {
      color: "#111111",
      fontWeight: "700",
      fontSize: 13,
    },
    sectionHeader: {
      marginTop: 26,
      marginBottom: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sectionTitle: {
      color: theme.colors.textPrimary,
      fontSize: 28,
      fontWeight: "700",
    },
    sectionAction: {
      color: theme.colors.accent,
      fontSize: 16,
      fontWeight: "700",
    },
    highlightList: {
      flexDirection: "row",
      columnGap: 10,
    },
    highlightCard: {
      flex: 1,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      padding: 12,
    },
    highlightBadge: {
      alignSelf: "flex-start",
      backgroundColor: theme.colors.primary,
      color: "#111111",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 10,
      fontSize: 11,
      fontWeight: "700",
    },
    highlightTitle: {
      marginTop: 10,
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: "700",
    },
    highlightSubtitle: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    campaignList: {
      rowGap: 10,
    },
    campaignCard: {
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      padding: 14,
    },
    campaignKicker: {
      color: theme.colors.accent,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    campaignTitle: {
      marginTop: 8,
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: "800",
    },
    campaignDescription: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    campaignAction: {
      marginTop: 10,
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    storyCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 14,
      rowGap: 12,
    },
    storyRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      columnGap: 10,
    },
    storyIndexBubble: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.colors.accent,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 2,
    },
    storyIndexText: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "700",
    },
    storyTextWrap: {
      flex: 1,
    },
    storyTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: "700",
    },
    storyDescription: {
      marginTop: 4,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
    },
    storeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 12,
    },
    beersRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 12,
    },
    storeCard: {
      width: "48.5%",
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    storeLogo: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surfaceElevated,
    },
    storeLogoText: {
      color: theme.colors.primary,
      fontWeight: "700",
      fontSize: 13,
    },
    storeName: {
      marginTop: 12,
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: "700",
    },
    storeTag: {
      marginTop: 4,
      color: theme.colors.accent,
      fontSize: 13,
      fontWeight: "600",
    },
    storeMeta: {
      marginTop: 6,
      color: theme.colors.textMuted,
      fontSize: 12,
      fontWeight: "500",
    },
  });
}
