import { StyleSheet } from "react-native";
import { theme } from "../../global/themes";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  contentContainer: {
    paddingTop: 64,
    paddingBottom: 140,
    paddingHorizontal: 20,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  addressText: {
    color: theme.colors.textPrimary,
    fontSize: 16,
    fontWeight: "600",
    maxWidth: "76%",
  },
  notificationButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.colors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
    position: "relative",
  },
  notificationIcon: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.colors.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  notificationBadgeText: {
    color: theme.colors.textPrimary,
    fontSize: 10,
    fontWeight: "700",
  },
  greetingRow: {
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  greetingText: {
    color: theme.colors.textPrimary,
    fontSize: 30,
    fontWeight: "700",
  },
  loginChip: {
    borderWidth: 1,
    borderColor: theme.colors.primaryDark,
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  loginChipText: {
    color: theme.colors.primary,
    fontWeight: "700",
    fontSize: 13,
  },
  guestHelperText: {
    marginTop: 10,
    color: theme.colors.textSecondary,
    fontSize: 14,
  },
  categoriesGrid: {
    marginTop: 22,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
  },
  categoryCard: {
    width: "23%",
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  categoryIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryIconText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: "700",
  },
  categoryLabel: {
    marginTop: 8,
    color: theme.colors.textPrimary,
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  bannerCard: {
    marginTop: 24,
    borderRadius: 24,
    backgroundColor: theme.colors.primaryDark,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.colors.primary,
  },
  bannerOverline: {
    color: theme.colors.primaryGlow,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  bannerTitle: {
    marginTop: 10,
    color: theme.colors.textPrimary,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 32,
  },
  bannerSubtitle: {
    marginTop: 10,
    color: theme.colors.textPrimary,
    opacity: 0.88,
    fontSize: 14,
    lineHeight: 20,
  },
  bannerButton: {
    marginTop: 16,
    alignSelf: "flex-start",
    borderRadius: 18,
    backgroundColor: theme.colors.textPrimary,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  bannerButtonText: {
    color: theme.colors.background,
    fontWeight: "700",
    fontSize: 13,
  },
  sectionHeader: {
    marginTop: 26,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontSize: 28,
    fontWeight: "700",
  },
  sectionAction: {
    color: theme.colors.primary,
    fontSize: 16,
    fontWeight: "700",
  },
  storeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
  },
  beersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
  },
  storeCard: {
    width: "48.5%",
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  storeLogo: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surfaceElevated,
  },
  storeLogoText: {
    color: theme.colors.primary,
    fontWeight: "700",
    fontSize: 13,
  },
  storeName: {
    marginTop: 12,
    color: theme.colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  storeTag: {
    marginTop: 4,
    color: theme.colors.success,
    fontSize: 13,
    fontWeight: "600",
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.surface,
    borderTopWidth: 1,
    borderColor: theme.colors.border,
    paddingTop: 10,
    paddingBottom: 20,
    paddingHorizontal: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bottomItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  bottomIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surfaceElevated,
  },
  bottomIconActive: {
    backgroundColor: theme.colors.primary,
  },
  bottomIconText: {
    color: theme.colors.textSecondary,
    fontSize: 10,
    fontWeight: "700",
  },
  bottomIconTextActive: {
    color: theme.colors.textOnPrimary,
  },
  bottomLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  bottomLabelActive: {
    color: theme.colors.textPrimary,
  },
});
