import { StyleSheet } from "react-native";
import { AppTheme } from "../../global/themes";

export function createStyles(theme: AppTheme) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    contentContainer: {
      paddingTop: 62,
      paddingBottom: 28,
      paddingHorizontal: 20,
    },
    topRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    topAction: {
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.border,
      borderWidth: 1,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    topActionText: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      fontWeight: "600",
    },
    cartAction: {
      marginBottom: 12,
      alignSelf: "flex-end",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    cartActionText: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    headerCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 18,
    },
    badge: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: theme.colors.surfaceElevated,
      alignItems: "center",
      justifyContent: "center",
    },
    badgeText: {
      color: theme.colors.primary,
      fontWeight: "700",
      fontSize: 14,
    },
    beerName: {
      marginTop: 12,
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: "800",
    },
    beerMeta: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 14,
    },
    beerPrice: {
      marginTop: 6,
      color: theme.colors.primaryGlow,
      fontSize: 16,
      fontWeight: "700",
    },
    infoCard: {
      marginTop: 14,
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 18,
      gap: 6,
    },
    sectionTitle: {
      marginTop: 8,
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    infoText: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 22,
    },
    ratingText: {
      color: theme.colors.success,
      fontWeight: "700",
      fontSize: 16,
    },
    linkText: {
      color: theme.colors.primary,
      fontWeight: "700",
      fontSize: 15,
      textDecorationLine: "underline",
    },
    quantityRow: {
      marginTop: 2,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    quantityButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surfaceElevated,
    },
    quantityButtonText: {
      color: theme.colors.textPrimary,
      fontWeight: "700",
      fontSize: 16,
    },
    quantityValue: {
      color: theme.colors.textPrimary,
      fontWeight: "800",
      fontSize: 15,
      minWidth: 24,
      textAlign: "center",
    },
    addOnCard: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceElevated,
      padding: 10,
    },
    addOnCardSelected: {
      borderColor: theme.colors.primary,
    },
    addOnTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    addOnLabel: {
      color: theme.colors.textPrimary,
      fontWeight: "700",
      fontSize: 14,
      flex: 1,
    },
    addOnPrice: {
      color: theme.colors.primaryGlow,
      fontWeight: "700",
      fontSize: 13,
    },
    addOnDescription: {
      marginTop: 4,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    addOnControlRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 10,
    },
    addOnQuantityValue: {
      minWidth: 20,
      textAlign: "center",
      color: theme.colors.textPrimary,
      fontWeight: "700",
      fontSize: 14,
    },
    previewTotalRow: {
      marginTop: 12,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    previewTotalLabel: {
      color: theme.colors.textSecondary,
      fontSize: 13,
    },
    previewTotalValue: {
      color: theme.colors.primaryGlow,
      fontSize: 15,
      fontWeight: "800",
    },
    upsellCard: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceElevated,
      padding: 10,
    },
    upsellRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    upsellName: {
      color: theme.colors.textPrimary,
      fontWeight: "700",
      fontSize: 14,
      flex: 1,
    },
    upsellPrice: {
      color: theme.colors.primaryGlow,
      fontWeight: "700",
      fontSize: 13,
    },
    upsellMeta: {
      marginTop: 4,
      color: theme.colors.textSecondary,
      fontSize: 12,
    },
    upsellAddButton: {
      marginTop: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      paddingVertical: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    upsellAddButtonText: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    primaryButton: {
      marginTop: 18,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      height: 52,
    },
    primaryButtonText: {
      color: theme.colors.textOnPrimary,
      fontWeight: "700",
      fontSize: 16,
    },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 30,
    },
    emptyTitle: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: "700",
      marginBottom: 12,
    },
    emptyButton: {
      borderRadius: 12,
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.border,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    emptyButtonText: {
      color: theme.colors.textPrimary,
      fontWeight: "600",
    },
  });
}
