import { StyleSheet } from "react-native";
import { AppTheme } from "../../global/themes";

export function createStyles(theme: AppTheme) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    contentContainer: {
      paddingTop: 62,
      paddingBottom: 120,
      paddingHorizontal: 20,
    },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 30,
      fontWeight: "800",
    },
    subtitle: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    sectionTitle: {
      marginTop: 22,
      marginBottom: 12,
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: "800",
    },
    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: 18,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 10,
    },
    consoleCard: {
      marginTop: 18,
      marginBottom: 4,
      padding: 16,
      borderRadius: 18,
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    consoleHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    consoleTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: "800",
    },
    availabilityButton: {
      paddingHorizontal: 12,
      height: 36,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    availabilityOn: {
      backgroundColor: theme.colors.success,
      borderColor: theme.colors.success,
    },
    availabilityOff: {
      backgroundColor: theme.colors.accentSoft,
      borderColor: theme.colors.error,
    },
    availabilityButtonText: {
      color: theme.colors.textOnPrimary,
      fontSize: 12,
      fontWeight: "800",
    },
    queueSummaryCard: {
      marginTop: 14,
      marginBottom: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    queueSummaryLabel: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: "600",
    },
    queueSummaryValue: {
      marginTop: 4,
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: "800",
    },
    queueColumns: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    queueColumnItem: {
      width: "48%",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    queueColumnLabel: {
      color: theme.colors.textSecondary,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: "600",
    },
    queueColumnValue: {
      marginTop: 3,
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: "800",
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    orderId: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: "700",
    },
    statusBadge: {
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    statusText: {
      fontSize: 11,
      fontWeight: "700",
    },
    cardText: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    messageText: {
      marginTop: 8,
      color: theme.colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "600",
    },
    timelineRow: {
      marginTop: 12,
      flexDirection: "row",
      gap: 6,
      alignItems: "center",
    },
    timelineDot: {
      flex: 1,
      height: 8,
      borderRadius: 999,
      backgroundColor: theme.colors.border,
    },
    timelineDotDone: {
      backgroundColor: theme.colors.primary,
    },
    timelineDotCurrent: {
      backgroundColor: theme.colors.accent,
    },
    timelineLabel: {
      marginTop: 8,
      color: theme.colors.textMuted,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "600",
    },
    advanceButton: {
      marginTop: 12,
      height: 42,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    advanceButtonText: {
      color: theme.colors.textOnPrimary,
      fontWeight: "800",
      fontSize: 13,
    },
    cancelButton: {
      marginTop: 8,
      height: 40,
      borderRadius: 12,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.error,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelButtonText: {
      color: theme.colors.error,
      fontWeight: "700",
      fontSize: 13,
    },
    consoleHint: {
      marginTop: 10,
      color: theme.colors.textMuted,
      fontSize: 12,
      lineHeight: 17,
    },
    notificationCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 12,
      marginBottom: 8,
    },
    notificationHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    notificationTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 13,
      fontWeight: "700",
    },
    channelBadge: {
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    channelPush: {
      backgroundColor: theme.colors.success,
    },
    channelInApp: {
      backgroundColor: theme.colors.warning,
    },
    channelBadgeText: {
      color: theme.colors.textOnPrimary,
      fontSize: 11,
      fontWeight: "700",
    },
    emptyCard: {
      marginTop: 20,
      backgroundColor: theme.colors.surface,
      borderRadius: 18,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    emptyText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    ctaButton: {
      marginTop: 14,
      height: 48,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    ctaButtonText: {
      color: theme.colors.textOnPrimary,
      fontWeight: "700",
      fontSize: 15,
    },
  });
}
